#ifndef JML_CONFIGURATION
#define JML_CONFIGURATION

#define DEBUGGER_ON
//#define UNIT_TEST_ON

#define LOG_LEVEL_CRITICAL	0
#define LOG_LEVEL_ERROR		1
#define LOG_LEVEL_WARNING	2
#define LOG_LEVEL_INFO		3
#define LOG_LEVEL_VERBOSE   4

#ifdef UNIT_TEST_ON
#define CURRENT_LOG_LEVEL	LOG_LEVEL_WARNING
#else
#define CURRENT_LOG_LEVEL	LOG_LEVEL_INFO
#endif

#endif //JML_CONFIGURATION